{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2a8a17d9-ded4-4381-980f-987b8afdb3cc",
   "metadata": {},
   "outputs": [],
   "source": [
    "#!/usr/bin/env python3\n",
    "\"\"\"\n",
    "🏆 Numerai Master Pipeline\n",
    "Combines Standard Models (LGBM, CatBoost, XGB) and Enhanced Models (Neural Net, Ensembles)\n",
    "\"\"\"\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import os\n",
    "import gc\n",
    "import sys\n",
    "import time\n",
    "import requests\n",
    "import warnings\n",
    "import pickle\n",
    "from pathlib import Path\n",
    "from datetime import datetime\n",
    "from tqdm import tqdm\n",
    "from numerapi import NumerAPI\n",
    "\n",
    "# Machine Learning Imports\n",
    "import lightgbm as lgb\n",
    "from xgboost import XGBRegressor\n",
    "\n",
    "# Try imports for optional libraries\n",
    "try:\n",
    "    from catboost import CatBoostRegressor\n",
    "    CATBOOST_AVAILABLE = True\n",
    "except ImportError:\n",
    "    CATBOOST_AVAILABLE = False\n",
    "    print(\"⚠️ CatBoost not found. Skipping CatBoost models.\")\n",
    "\n",
    "try:\n",
    "    import torch\n",
    "    import torch.nn as nn\n",
    "    import torch.optim as optim\n",
    "    from torch.utils.data import Dataset, DataLoader\n",
    "    PYTORCH_AVAILABLE = True\n",
    "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "except ImportError:\n",
    "    PYTORCH_AVAILABLE = False\n",
    "    print(\"⚠️ PyTorch not found. Skipping Neural Network models.\")\n",
    "\n",
    "# Try to import your custom feature engineer\n",
    "try:\n",
    "    from numerai_feature_engineering import NumeraiFeatureEngineer, get_all_feature_columns\n",
    "    FEATURE_ENG_AVAILABLE = True\n",
    "except ImportError:\n",
    "    FEATURE_ENG_AVAILABLE = False\n",
    "    print(\"⚠️ 'numerai_feature_engineering.py' not found. Skipping Enhanced models.\")\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# ============================================================\n",
    "# CONFIGURATION\n",
    "# ============================================================\n",
    "\n",
    "# API Keys (Priority: Env Vars -> Manual Fallback)\n",
    "PUBLIC_ID = os.getenv(\"NUMERAI_PUBLIC_ID\")\n",
    "SECRET_KEY = os.getenv(\"NUMERAI_SECRET_KEY\")\n",
    "\n",
    "# Model Definitions\n",
    "MODELS = {\n",
    "    # Standard Models (Raw Features)\n",
    "    'lightgbm': {'id': 'bd2f8540-d90a-4206-b1c5-4e28f2865cba', 'name': 'jewellzilla_std'},\n",
    "    'catboost': {'id': '9e253cd6-6b6b-4178-a641-c9738f21eb11', 'name': 'jewellzilla_cat'},\n",
    "    'xgboost':  {'id': 'a65acf61-b5ba-4982-a7c8-7339be001a13', 'name': 'jewellzilla_xg'},\n",
    "    \n",
    "    # Enhanced Models (Engineered Features)\n",
    "    'enh_lgbm': {'id': 'e02eda5d-1760-4984-a6c2-526a876621fb', 'name': 'jewellzilla_std_enh'},\n",
    "    'enh_xgboost': {'id': '98639631-99f8-4139-b069-21fdc094a074', 'name': 'jewellzilla_xg_enh'},\n",
    "    'enh_nn': {'id': '548df016-74d2-4e9b-9164-ee4165e19a7e', 'name': 'jewellzilla_nn'},\n",
    "    'enh_rank_ens': {'id': 'ed68de39-57f8-43d2-92ce-3a6e375f4b8a', 'name': 'jewellzilla_rank_ens'}\n",
    "}\n",
    "\n",
    "# Settings\n",
    "DATA_VERSION = \"v5.2\"\n",
    "TRAINING_FILE = f\"{DATA_VERSION}/train.parquet\"\n",
    "LIVE_FILE = f\"{DATA_VERSION}/live.parquet\"\n",
    "SUBMISSIONS_DIR = Path(\"submissions\")\n",
    "SUBMISSIONS_DIR.mkdir(exist_ok=True)\n",
    "DATE_STR = datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "\n",
    "# Memory & Training Settings\n",
    "SAMPLE_FRACTION = 0.08  # For Standard Models\n",
    "ENHANCED_ROWS = 200000  # For Enhanced Models\n",
    "MAX_FEATURES = 750      # For Standard Models\n",
    "\n",
    "# ============================================================\n",
    "# HELPER CLASSES & FUNCTIONS\n",
    "# ============================================================\n",
    "\n",
    "def download_with_retry(napi, filename, max_retries=10, chunk_size=1024*1024):\n",
    "    \"\"\"Robust download with resume support.\"\"\"\n",
    "    dest_path = Path(filename)\n",
    "    dest_path.parent.mkdir(parents=True, exist_ok=True)\n",
    "    \n",
    "    query = \"query($filename: String!) { dataset(filename: $filename) }\"\n",
    "    args = {'filename': filename}\n",
    "    url = napi.raw_query(query, args)['data']['dataset']\n",
    "    \n",
    "    print(f\"\\n📥 Downloading {filename}...\")\n",
    "    for attempt in range(max_retries):\n",
    "        try:\n",
    "            resume_pos = 0\n",
    "            mode = 'wb'\n",
    "            if dest_path.exists():\n",
    "                resume_pos = dest_path.stat().st_size\n",
    "                mode = 'ab'\n",
    "            \n",
    "            headers = {'Range': f'bytes={resume_pos}-'} if resume_pos > 0 else {}\n",
    "            response = requests.get(url, headers=headers, stream=True, timeout=30)\n",
    "            \n",
    "            total_size = int(response.headers.get('content-length', 0)) + resume_pos\n",
    "            if 'content-range' in response.headers:\n",
    "                total_size = int(response.headers['content-range'].split('/')[-1])\n",
    "\n",
    "            with open(dest_path, mode) as f:\n",
    "                with tqdm(total=total_size, initial=resume_pos, unit='B', unit_scale=True, disable=None) as pbar:\n",
    "                    for chunk in response.iter_content(chunk_size=chunk_size):\n",
    "                        if chunk:\n",
    "                            f.write(chunk)\n",
    "                            pbar.update(len(chunk))\n",
    "            \n",
    "            if dest_path.stat().st_size >= total_size:\n",
    "                print(\"   ✅ Download complete!\")\n",
    "                return True\n",
    "        except Exception as e:\n",
    "            print(f\"   ⚠️ Attempt {attempt+1} failed: {e}\")\n",
    "            time.sleep(5)\n",
    "    return False\n",
    "\n",
    "if PYTORCH_AVAILABLE:\n",
    "    class NumeraiDataset(Dataset):\n",
    "        def __init__(self, features, targets):\n",
    "            self.features = torch.FloatTensor(features)\n",
    "            self.targets = torch.FloatTensor(targets)\n",
    "        def __len__(self): return len(self.features)\n",
    "        def __getitem__(self, idx): return self.features[idx], self.targets[idx]\n",
    "\n",
    "    class NumeraiNN(nn.Module):\n",
    "        def __init__(self, input_dim):\n",
    "            super(NumeraiNN, self).__init__()\n",
    "            self.network = nn.Sequential(\n",
    "                nn.Linear(input_dim, 512), nn.BatchNorm1d(512), nn.ReLU(), nn.Dropout(0.3),\n",
    "                nn.Linear(512, 256), nn.BatchNorm1d(256), nn.ReLU(), nn.Dropout(0.3),\n",
    "                nn.Linear(256, 128), nn.BatchNorm1d(128), nn.ReLU(), nn.Dropout(0.2),\n",
    "                nn.Linear(128, 64), nn.ReLU(), nn.Dropout(0.2),\n",
    "                nn.Linear(64, 1), nn.Sigmoid()\n",
    "            )\n",
    "        def forward(self, x): return self.network(x)\n",
    "\n",
    "# ============================================================\n",
    "# MAIN EXECUTION\n",
    "# ============================================================\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    print(\"=\"*70)\n",
    "    print(\"🏆 NUMERAI MASTER PIPELINE\")\n",
    "    print(\"=\"*70)\n",
    "\n",
    "    # 1. Connect\n",
    "    if not PUBLIC_ID or not SECRET_KEY:\n",
    "        raise ValueError(\"❌ API keys missing! Set NUMERAI_PUBLIC_ID and NUMERAI_SECRET_KEY.\")\n",
    "    napi = NumerAPI(PUBLIC_ID, SECRET_KEY)\n",
    "    print(f\"✅ Connected as {napi.get_account()['username']}\")\n",
    "\n",
    "    # 2. Download Data\n",
    "    if not Path(TRAINING_FILE).exists():\n",
    "        download_with_retry(napi, TRAINING_FILE)\n",
    "    \n",
    "    # Always get fresh live data\n",
    "    if Path(LIVE_FILE).exists(): os.remove(LIVE_FILE)\n",
    "    download_with_retry(napi, LIVE_FILE)\n",
    "\n",
    "    # Dictionary to store file paths for submission\n",
    "    submission_files = {}\n",
    "\n",
    "    # ========================================================\n",
    "    # PHASE 1: STANDARD MODELS (Raw Features)\n",
    "    # ========================================================\n",
    "    print(\"\\n\" + \"=\"*70)\n",
    "    print(\"🚀 PHASE 1: STANDARD MODELS (Raw Features)\")\n",
    "    print(\"=\"*70)\n",
    "\n",
    "    import pyarrow.parquet as pq\n",
    "    pq_file = pq.ParquetFile(TRAINING_FILE)\n",
    "    all_cols = pq_file.schema.names\n",
    "    feature_cols = [c for c in all_cols if c.startswith(\"feature_\")][:MAX_FEATURES]\n",
    "    cols_to_load = feature_cols + [\"target\"]\n",
    "\n",
    "    # Load Data (Standard)\n",
    "    print(\"🔄 Loading standard training data...\")\n",
    "    total_rows = pq_file.metadata.num_rows\n",
    "    sample_size = int(total_rows * SAMPLE_FRACTION)\n",
    "    \n",
    "    df_train = pd.read_parquet(TRAINING_FILE, columns=cols_to_load).sample(n=sample_size, random_state=42)\n",
    "    df_live = pd.read_parquet(LIVE_FILE, columns=feature_cols)\n",
    "    \n",
    "    X_train = df_train[feature_cols]\n",
    "    y_train = df_train[\"target\"]\n",
    "    \n",
    "    # --- LightGBM Standard ---\n",
    "    print(\"\\n🌲 Training Standard LightGBM...\")\n",
    "    model = lgb.LGBMRegressor(n_estimators=1000, learning_rate=0.05, max_depth=4, num_leaves=16, colsample_bytree=0.1, n_jobs=-1, verbose=-1)\n",
    "    model.fit(X_train, y_train)\n",
    "    preds = model.predict(df_live)\n",
    "    preds_norm = (preds - preds.min()) / (preds.max() - preds.min())\n",
    "    \n",
    "    fname = SUBMISSIONS_DIR / f\"std_lgbm_{DATE_STR}.csv\"\n",
    "    pd.DataFrame({\"id\": df_live.index, \"prediction\": preds_norm}).to_csv(fname, index=False)\n",
    "    submission_files['lightgbm'] = fname\n",
    "    print(f\"   ✅ Saved {fname}\")\n",
    "\n",
    "    # --- XGBoost Standard ---\n",
    "    print(\"\\n🚀 Training Standard XGBoost...\")\n",
    "    model = XGBRegressor(n_estimators=1000, learning_rate=0.05, max_depth=4, colsample_bytree=0.1, n_jobs=-1, verbosity=0)\n",
    "    model.fit(X_train, y_train)\n",
    "    preds = model.predict(df_live)\n",
    "    preds_norm = (preds - preds.min()) / (preds.max() - preds.min())\n",
    "    \n",
    "    fname = SUBMISSIONS_DIR / f\"std_xgb_{DATE_STR}.csv\"\n",
    "    pd.DataFrame({\"id\": df_live.index, \"prediction\": preds_norm}).to_csv(fname, index=False)\n",
    "    submission_files['xgboost'] = fname\n",
    "    print(f\"   ✅ Saved {fname}\")\n",
    "\n",
    "    # --- CatBoost Standard ---\n",
    "    if CATBOOST_AVAILABLE:\n",
    "        print(\"\\n🐱 Training Standard CatBoost...\")\n",
    "        model = CatBoostRegressor(iterations=1000, learning_rate=0.05, depth=4, verbose=False)\n",
    "        model.fit(X_train, y_train)\n",
    "        preds = model.predict(df_live)\n",
    "        preds_norm = (preds - preds.min()) / (preds.max() - preds.min())\n",
    "        \n",
    "        fname = SUBMISSIONS_DIR / f\"std_cat_{DATE_STR}.csv\"\n",
    "        pd.DataFrame({\"id\": df_live.index, \"prediction\": preds_norm}).to_csv(fname, index=False)\n",
    "        submission_files['catboost'] = fname\n",
    "        print(f\"   ✅ Saved {fname}\")\n",
    "\n",
    "    # Clean up memory before Phase 2\n",
    "    del df_train, X_train, y_train, model, preds\n",
    "    gc.collect()\n",
    "\n",
    "    # ========================================================\n",
    "    # PHASE 2: ENHANCED MODELS (Engineered Features)\n",
    "    # ========================================================\n",
    "    if FEATURE_ENG_AVAILABLE:\n",
    "        print(\"\\n\" + \"=\"*70)\n",
    "        print(\"🧪 PHASE 2: ENHANCED MODELS (Feature Engineering)\")\n",
    "        print(\"=\"*70)\n",
    "\n",
    "        # Reload data for Feature Engineering (might need more cols or different sample)\n",
    "        print(\"🔄 Loading data for engineering...\")\n",
    "        df_train = pd.read_parquet(TRAINING_FILE).sample(n=ENHANCED_ROWS, random_state=42)\n",
    "        df_live = pd.read_parquet(LIVE_FILE)\n",
    "\n",
    "        print(\"🔧 Running Feature Engineering (this takes time)...\")\n",
    "        if os.path.exists('feature_engineer.pkl'):\n",
    "            fe = NumeraiFeatureEngineer.load('feature_engineer.pkl')\n",
    "            df_train = fe.transform(df_train)\n",
    "            df_live = fe.transform(df_live)\n",
    "        else:\n",
    "            fe = NumeraiFeatureEngineer()\n",
    "            df_train = fe.fit_transform(df_train)\n",
    "            df_live = fe.transform(df_live)\n",
    "            fe.save('feature_engineer.pkl')\n",
    "\n",
    "        # Select Features\n",
    "        all_feats = get_all_feature_columns(df_train)\n",
    "        corrs = df_train[all_feats].corrwith(df_train['target']).abs()\n",
    "        top_features = corrs.nlargest(2000).index.tolist()\n",
    "        \n",
    "        X_train_eng = df_train[top_features].values\n",
    "        y_train_eng = df_train['target'].values\n",
    "        X_live_eng = df_live[top_features].values\n",
    "        \n",
    "        live_preds = pd.DataFrame(index=df_live.index)\n",
    "\n",
    "        # --- Enhanced LGBM ---\n",
    "        print(\"\\n🌲 Training Enhanced LightGBM...\")\n",
    "        model = lgb.LGBMRegressor(n_estimators=2000, learning_rate=0.01, max_depth=5, num_leaves=32, colsample_bytree=0.1, n_jobs=-1, verbose=-1)\n",
    "        model.fit(X_train_eng, y_train_eng)\n",
    "        live_preds['lgbm'] = model.predict(X_live_eng)\n",
    "        \n",
    "        fname = SUBMISSIONS_DIR / f\"enh_lgbm_{DATE_STR}.csv\"\n",
    "        live_preds[['lgbm']].rename(columns={'lgbm': 'prediction'}).to_csv(fname)\n",
    "        submission_files['enh_lgbm'] = fname\n",
    "\n",
    "        # --- Enhanced XGBoost ---\n",
    "        print(\"\\n🚀 Training Enhanced XGBoost...\")\n",
    "        model = XGBRegressor(n_estimators=2000, learning_rate=0.01, max_depth=5, colsample_bytree=0.1, n_jobs=-1, verbosity=0)\n",
    "        model.fit(X_train_eng, y_train_eng)\n",
    "        live_preds['xgb'] = model.predict(X_live_eng)\n",
    "        \n",
    "        fname = SUBMISSIONS_DIR / f\"enh_xgb_{DATE_STR}.csv\"\n",
    "        live_preds[['xgb']].rename(columns={'xgb': 'prediction'}).to_csv(fname)\n",
    "        submission_files['enh_xgboost'] = fname\n",
    "\n",
    "        # --- Enhanced Neural Net ---\n",
    "        if PYTORCH_AVAILABLE:\n",
    "            print(\"\\n🧠 Training Neural Network...\")\n",
    "            train_ds = NumeraiDataset(X_train_eng, y_train_eng)\n",
    "            train_loader = DataLoader(train_ds, batch_size=2048, shuffle=True)\n",
    "            \n",
    "            nn_model = NumeraiNN(len(top_features)).to(device)\n",
    "            optimizer = optim.Adam(nn_model.parameters(), lr=0.001)\n",
    "            criterion = nn.MSELoss()\n",
    "            \n",
    "            nn_model.train()\n",
    "            for epoch in range(50): # Reduced epochs for daily speed\n",
    "                for batch_x, batch_y in train_loader:\n",
    "                    batch_x, batch_y = batch_x.to(device), batch_y.to(device)\n",
    "                    optimizer.zero_grad()\n",
    "                    loss = criterion(nn_model(batch_x).squeeze(), batch_y)\n",
    "                    loss.backward()\n",
    "                    optimizer.step()\n",
    "            \n",
    "            nn_model.eval()\n",
    "            with torch.no_grad():\n",
    "                live_tensor = torch.FloatTensor(X_live_eng).to(device)\n",
    "                live_preds['nn'] = nn_model(live_tensor).cpu().numpy().flatten()\n",
    "            \n",
    "            fname = SUBMISSIONS_DIR / f\"enh_nn_{DATE_STR}.csv\"\n",
    "            live_preds[['nn']].rename(columns={'nn': 'prediction'}).to_csv(fname)\n",
    "            submission_files['enh_nn'] = fname\n",
    "\n",
    "        # --- Enhanced Ensemble ---\n",
    "        print(\"\\n⚖️ Creating Ensemble...\")\n",
    "        cols = [c for c in ['lgbm', 'xgb', 'nn'] if c in live_preds.columns]\n",
    "        for c in cols:\n",
    "            live_preds[f'{c}_rank'] = live_preds[c].rank(pct=True)\n",
    "        \n",
    "        live_preds['ensemble'] = live_preds[[f'{c}_rank' for c in cols]].mean(axis=1)\n",
    "        \n",
    "        fname = SUBMISSIONS_DIR / f\"enh_ensemble_{DATE_STR}.csv\"\n",
    "        live_preds[['ensemble']].rename(columns={'ensemble': 'prediction'}).to_csv(fname)\n",
    "        submission_files['enh_rank_ens'] = fname\n",
    "\n",
    "    # ========================================================\n",
    "    # PHASE 3: SUBMISSIONS\n",
    "    # ========================================================\n",
    "    print(\"\\n\" + \"=\"*70)\n",
    "    print(\"📤 PHASE 3: UPLOADING SUBMISSIONS\")\n",
    "    print(\"=\"*70)\n",
    "\n",
    "    for key, fpath in submission_files.items():\n",
    "        if key in MODELS:\n",
    "            model_conf = MODELS[key]\n",
    "            print(f\"Uploading {key} -> {model_conf['name']}...\")\n",
    "            try:\n",
    "                submission_id = napi.upload_predictions(fpath, model_id=model_conf['id'])\n",
    "                print(f\"   ✅ Success! ID: {submission_id}\")\n",
    "            except Exception as e:\n",
    "                print(f\"   ❌ Failed: {e}\")\n",
    "        else:\n",
    "            print(f\"⚠️  Skipping upload for {key} (No ID found in configuration)\")\n",
    "\n",
    "    print(\"\\n✅ MASTER PIPELINE COMPLETE\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
