name: Numerai Daily Master Pipeline

on:
  schedule:
    - cron: '0 13 * * *' # 1 PM UTC daily
  workflow_dispatch:      # Allows manual trigger button

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Master Submission Script
        env:
          NUMERAI_PUBLIC_ID: ${{ secrets.NUMERAI_PUBLIC_ID }}
          NUMERAI_SECRET_KEY: ${{ secrets.NUMERAI_SECRET_KEY }}
        run: python master_submission.py
